export enum AdminErrorCode {
  // Patients
  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  PATIENT_CREATE_FAILED = 'PATIENT_CREATE_FAILED',
  PATIENT_UPDATE_FAILED = 'PATIENT_UPDATE_FAILED',
  INVALID_COORDINATOR = 'INVALID_COORDINATOR',

  // Staff
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_CREATE_FAILED = 'STAFF_CREATE_FAILED',
  STAFF_UPDATE_FAILED = 'STAFF_UPDATE_FAILED',
  DUPLICATE_LOGIN_ID = 'DUPLICATE_LOGIN_ID',
  PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',
  CANNOT_DEACTIVATE_SELF = 'CANNOT_DEACTIVATE_SELF',

  // Schedule
  SCHEDULE_PATTERN_UPDATE_FAILED = 'SCHEDULE_PATTERN_UPDATE_FAILED',
  SCHEDULE_ALREADY_EXISTS = 'SCHEDULE_ALREADY_EXISTS',
  SCHEDULE_CREATE_FAILED = 'SCHEDULE_CREATE_FAILED',
  SCHEDULE_DELETE_FAILED = 'SCHEDULE_DELETE_FAILED',
  CANNOT_DELETE_AUTO_SCHEDULE = 'CANNOT_DELETE_AUTO_SCHEDULE',
  SCHEDULE_GENERATE_FAILED = 'SCHEDULE_GENERATE_FAILED',

  // Room Mapping
  ROOM_MAPPING_ALREADY_EXISTS = 'ROOM_MAPPING_ALREADY_EXISTS',
  ROOM_MAPPING_CREATE_FAILED = 'ROOM_MAPPING_CREATE_FAILED',

  // Stats
  STATS_FETCH_FAILED = 'STATS_FETCH_FAILED',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
}

export class AdminError extends Error {
  constructor(
    public code: AdminErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'AdminError';
  }
}
