-- Migration: 의사 및 환자 시드 데이터
-- CSV 파일에서 호실 3101 이상 환자 데이터 추출

-- 1. 의사(주치의) 데이터 삽입 (staff 테이블)
-- 중복 방지를 위해 ON CONFLICT 사용
INSERT INTO staff (login_id, password_hash, name, role, is_active)
VALUES
  ('doctor_parkmh', '$2b$10$defaulthash', '박명현', 'doctor', true),
  ('doctor_leesc', '$2b$10$defaulthash', '이상철', 'doctor', true),
  ('doctor_kwondh', '$2b$10$defaulthash', '권도훈', 'doctor', true),
  ('doctor_shinjw', '$2b$10$defaulthash', '신정욱', 'doctor', true),
  ('doctor_parksu', '$2b$10$defaulthash', '박상운', 'doctor', true),
  ('doctor_leesh', '$2b$10$defaulthash', '이신화', 'doctor', true),
  ('doctor_parksh', '$2b$10$defaulthash', '박승현', 'doctor', true)
ON CONFLICT (login_id) DO NOTHING;

-- 2. 환자 데이터 삽입 (호실 3101 이상)
-- 의사 ID를 서브쿼리로 참조
INSERT INTO patients (name, gender, room_number, patient_id_no, doctor_id, status, memo)
VALUES
  -- 3101 호실
  ('이득환', 'M', '3101', '100698', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이점순', 'F', '3101', '103004', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김봉석', 'M', '3101', '501306', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('오기용', 'M', '3101', '986333', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김무애', 'F', '3101', '995326', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김선정', 'F', '3101', '996053', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백진주', 'F', '3101', '2006350', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김지양', 'M', '3101', '2010612', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김은정', 'F', '3101', '2011935', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('황보재연', 'M', '3101', '2031329', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김진석', 'M', '3101', '2041909', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('허준석', 'M', '3101', '2050763', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤외태', 'M', '3101', '2090300', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤성훈', 'M', '3101', '2101379', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정창호', 'M', '3101', '2107804', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박옥선', 'F', '3101', '2109189', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최영수', 'M', '3101', '2113476', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최영일', 'M', '3101', '2118912', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김민자', 'F', '3101', '2118915', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('진현주', 'F', '3101', '2119272', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이인숙', 'F', '3101', '2127540', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이승민', 'M', '3101', '2127606', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김세은', 'F', '3101', '2130434', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('문서옥', 'F', '3101', '2201551', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김태형', 'M', '3101', '2222535', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박종현', 'M', '3101', '2223613', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박창민', 'M', '3101', '2230452', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조승애', 'F', '3101', '2230494', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('진상훈', 'M', '3101', '2231460', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박종용', 'M', '3101', '2233864', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤정화', 'F', '3101', '2245121', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이현승', 'M', '3101', '2250961', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3102 호실
  ('박경건', 'M', '3102', '101860', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('송용진', 'M', '3102', '102034', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이옥순', 'F', '3102', '103107', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('양애순', 'F', '3102', '103455', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('송재영', 'M', '3102', '103521', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최주영', 'M', '3102', '103721', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정경미', 'F', '3102', '104703', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김희창', 'M', '3102', '970299', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김주형', 'M', '3102', '970665', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이승현', 'F', '3102', '972918', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김경희', 'F', '3102', '2002251', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('배미정', 'F', '3102', '2031595', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박노훈', 'M', '3102', '2031761', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김정희', 'F', '3102', '2032607', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김광분', 'F', '3102', '2051152', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최덕림', 'M', '3102', '2060314', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최은규', 'F', '3102', '2061794', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신현숙', 'F', '3102', '2070401', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손정훈', 'M', '3102', '2090506', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정재만', 'M', '3102', '2090974', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('황재희', 'M', '3102', '2101771', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정원', 'M', '3102', '2101913', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤경숙', 'F', '3102', '2103492', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('노해경', 'F', '3102', '2106437', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박상정', 'M', '3102', '2108640', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이현주', 'F', '3102', '2119241', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박찬혁', 'M', '3102', '2124371', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이선호', 'M', '3102', '2135476', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이동철', 'M', '3102', '2136750', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이영숙', 'F', '3102', '2202167', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박구훈', 'M', '3102', '2221205', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김주안', 'M', '3102', '2252208', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('진호성', 'M', '3102', '2252724', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김세진', 'F', '3102', '2253156', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3103 호실
  ('최태순', 'F', '3103', '101273', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('류대군', 'M', '3103', '101781', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김무숙', 'F', '3103', '102694', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김학로', 'M', '3103', '103977', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최정애', 'F', '3103', '105165', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이선호', 'M', '3103', '105174', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전한기', 'M', '3103', '970852', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('임명숙', 'F', '3103', '2013223', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이광직', 'M', '3103', '2050588', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김병규', 'M', '3103', '2091724', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김인대', 'M', '3103', '2100053', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조주영', 'M', '3103', '2101219', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정희', 'M', '3103', '2101247', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정원', 'M', '3103', '2104485', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백승권', 'M', '3103', '2107092', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('진광일', 'M', '3103', '2110424', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장태영', 'M', '3103', '2112345', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('엄두용', 'M', '3103', '2114177', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조경화', 'F', '3103', '2114511', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조우혁', 'M', '3103', '2115459', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신병민', 'M', '3103', '2116624', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('권형철', 'M', '3103', '2121021', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('한명수', 'M', '3103', '2121156', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김상섭', 'M', '3103', '2126267', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전현주', 'F', '3103', '2128858', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박미경', 'F', '3103', '2202059', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('권도혁', 'M', '3103', '2202400', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('한수자', 'F', '3103', '2212693', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('강은영', 'F', '3103', '2222626', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('서완덕', 'M', '3103', '2232435', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이혜진', 'F', '3103', '2232708', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이석주', 'M', '3103', '2245111', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3104 호실
  ('전경훈', 'M', '3104', '100787', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박재현', 'M', '3104', '101671', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('구영숙', 'F', '3104', '103524', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박정욱', 'M', '3104', '104316', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김주리', 'F', '3104', '104720', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장재호', 'M', '3104', '104787', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('도기태', 'M', '3104', '105111', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정하영', 'F', '3104', '105561', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전용환', 'M', '3104', '970016', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('임명숙', 'F', '3104', '992437', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최은지', 'F', '3104', '2003170', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김미애', 'F', '3104', '2030496', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신주영', 'M', '3104', '2030963', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손홍관', 'M', '3104', '2051050', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('배상흥', 'M', '3104', '2060602', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김영목', 'M', '3104', '2062029', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김희구', 'M', '3104', '2080988', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최지훈', 'M', '3104', '2082554', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백홍기', 'M', '3104', '2101050', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조재열', 'M', '3104', '2106957', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('임현정', 'F', '3104', '2114545', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박영보', 'M', '3104', '2116203', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('서정인', 'M', '3104', '2120494', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('남종우', 'M', '3104', '2127434', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('남대식', 'M', '3104', '2129822', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김유미', 'F', '3104', '2130965', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장덕기', 'M', '3104', '2132696', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전은혜', 'F', '3104', '2137404', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이연옥', 'F', '3104', '2200901', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김동우', 'M', '3104', '2210004', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정현이', 'F', '3104', '2210973', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박혜진', 'F', '3104', '2220461', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김향수', 'M', '3104', '2252400', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3105 호실
  ('위선희', 'F', '3105', '101634', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백숙희', 'F', '3105', '102081', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('우창형', 'M', '3105', '102226', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('서동훈', 'M', '3105', '102467', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('석미순', 'F', '3105', '102470', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최의환', 'M', '3105', '102496', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이경영', 'F', '3105', '103035', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신은옥', 'F', '3105', '104030', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이규진', 'M', '3105', '104598', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조현철', 'M', '3105', '105078', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이장환', 'M', '3105', '105162', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('황규필', 'M', '3105', '983153', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정춘희', 'F', '3105', '2005372', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전희진', 'F', '3105', '2005716', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최정실', 'F', '3105', '2050108', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정지은', 'F', '3105', '2051403', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김종근', 'M', '3105', '2061676', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('안희련', 'F', '3105', '2080762', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김민경', 'F', '3105', '2091002', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('허규호', 'M', '3105', '2101857', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('임미희', 'F', '3105', '2111230', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('서오영', 'F', '3105', '2113851', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤호규', 'M', '3105', '2114475', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('안병열', 'M', '3105', '2115780', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이미경', 'F', '3105', '2115993', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최수현', 'F', '3105', '2117226', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김태우', 'M', '3105', '2118539', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장민경', 'F', '3105', '2127344', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김상숙', 'F', '3105', '2128465', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손은미', 'F', '3105', '2139105', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백자원', 'M', '3105', '2141240', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김도희', 'F', '3105', '2245970', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최명숙', 'F', '3105', '2246191', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장언수', 'F', '3105', '2247959', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정선희', 'F', '3105', '2248152', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3106 호실
  ('최용석', 'M', '3106', '102706', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이엽', 'M', '3106', '102857', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('류선자', 'F', '3106', '102998', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신참나', 'F', '3106', '103228', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김재용', 'M', '3106', '103707', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정옥조', 'F', '3106', '103985', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박귀선', 'F', '3106', '104406', (SELECT id FROM staff WHERE name = '이신화' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박재현', 'M', '3106', '973700', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이동희', 'F', '3106', '974373', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조민지', 'F', '3106', '980410', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손선락', 'M', '3106', '995609', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김철영', 'M', '3106', '2003366', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('신은경', 'F', '3106', '2020719', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이승희', 'F', '3106', '2022320', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김태조', 'M', '3106', '2022374', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이상재', 'M', '3106', '2030954', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤초희', 'F', '3106', '2032424', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('제종규', 'M', '3106', '2051121', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김민정', 'F', '3106', '2052186', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('조영도', 'M', '3106', '2062328', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김대진', 'M', '3106', '2080995', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김순범', 'M', '3106', '2081004', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('임혁규', 'M', '3106', '2081110', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('여도균', 'M', '3106', '2111258', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김정훈', 'M', '3106', '2116619', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박준희', 'M', '3106', '2119920', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김새슬', 'F', '3106', '2122655', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정옥', 'F', '3106', '2124808', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('구자규', 'M', '3106', '2203032', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정준혁', 'M', '3106', '2210311', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('오동욱', 'M', '3106', '2220529', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손영칠', 'M', '3106', '2223568', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('송덕재', 'M', '3106', '2230300', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이하은', 'F', '3106', '2248762', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이희정', 'F', '3106', '2251303', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3111 호실
  ('이동구', 'M', '3111', '101338', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이대희', 'M', '3111', '105325', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최윤희', 'F', '3111', '2022274', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박중용', 'M', '3111', '2050913', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박진영', 'M', '3111', '2119106', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최진혁', 'M', '3111', '2131171', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('손혜영', 'F', '3111', '2133506', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정성훈', 'M', '3111', '2137981', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정희주', 'F', '3111', '2200656', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이명자', 'F', '3111', '2210319', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이호덕', 'M', '3111', '2222264', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3114 호실
  ('손배헌', 'M', '3114', '101613', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('함현숙', 'F', '3114', '102128', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김명호', 'M', '3114', '102266', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전경진', 'M', '3114', '103423', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이은경', 'F', '3114', '104558', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박찬동', 'M', '3114', '104663', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('구태성', 'M', '3114', '104697', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이용희', 'M', '3114', '105063', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김선자', 'F', '3114', '105096', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박자경', 'F', '3114', '970032', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('윤상수', 'M', '3114', '970278', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이혜현', 'F', '3114', '970780', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정호', 'F', '3114', '983476', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('배창호', 'M', '3114', '2005827', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('시지안', 'F', '3114', '2061138', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박제훈', 'M', '3114', '2061254', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김동현', 'M', '3114', '2071360', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이재희', 'F', '3114', '2109158', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('장영홍', 'M', '3114', '2116611', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박영민', 'M', '3114', '2120460', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('백승영', 'M', '3114', '2122070', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김향란', 'F', '3114', '2123539', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('전혜심', 'F', '3114', '2124334', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이정희', 'F', '3114', '2125598', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이경은', 'F', '3114', '2126855', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박재영', 'M', '3114', '2127965', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('권정안', 'M', '3114', '2129928', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최천호', 'M', '3114', '2131049', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김선욱', 'M', '3114', '2131868', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('문수연', 'F', '3114', '2135226', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('배석준', 'M', '3114', '2135331', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최용은', 'F', '3114', '2211067', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박해진', 'M', '3114', '2213737', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이상윤', 'M', '3114', '2233167', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),

  -- 3118 호실
  ('김병훈', 'M', '3118', '2024316', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김태희', 'F', '3118', '2101780', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('문정희', 'F', '3118', '2105174', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정연섭', 'M', '3118', '2106883', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('성귀영', 'M', '3118', '2117412', (SELECT id FROM staff WHERE name = '이상철' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('이연우', 'F', '3118', '2125001', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('안상헌', 'M', '3118', '2129892', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김민우', 'M', '3118', '2133695', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김예진', 'F', '3118', '2202433', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('최원재', 'M', '3118', '2210157', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('오형석', 'M', '3118', '2220567', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김영욱', 'M', '3118', '2247000', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('정지윤', 'F', '3118', '2251861', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('박수빈', 'F', '3118', '2252245', (SELECT id FROM staff WHERE name = '박명현' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('김가영', 'F', '3118', '2252459', (SELECT id FROM staff WHERE name = '권도훈' AND role = 'doctor' LIMIT 1), 'active', NULL),
  ('류세영', 'F', '3118', '2253155', (SELECT id FROM staff WHERE name = '박상운' AND role = 'doctor' LIMIT 1), 'active', NULL)
ON CONFLICT (patient_id_no) DO UPDATE SET
  name = EXCLUDED.name,
  gender = EXCLUDED.gender,
  room_number = EXCLUDED.room_number,
  doctor_id = EXCLUDED.doctor_id;
